### ISSUE TITLE
Question re: BOM

### ISSUE THREAD

**Issue by snhirsch** [JohnDMcMaster/8051dumper#1]
Your BOM calls out all resistors as 1% parts.  Is anything in the circuit critical enough to require precision parts?

I'm also curious about the need for C5 and C6 to be non-polarized.  From looking at the schematic it appears that tantalum or electrolytic parts would be fine.  

Can you clarify?  Thanks.

**Comment by JohnDMcMaster** [comment]
Hi there! This is a fork of another's project. Please ask the question here: https://gitlab.com/NF6X_Retrocomputing/8051dumper

**Comment by snhirsch** [comment]
Ah - thanks, John.  Did you introduce mods to the hardware, software, both?  Just curious.
